### ISSUE TITLE
[Bug]: The saved password is not hashed

### ISSUE THREAD

**Issue by masetto** [eighty9nine/filament-password-expiry#4]
### What happened?

The password is saved in clear, without hashing: https://github.com/eighty9nine/filament-password-expiry/blob/3.x/src/Pages/ResetPassword.php#L156

I think you have to update from 
```
$authObject->{config('password-expiry.password_column_name')} = $data['password'];
```

to

```
$authObject->{config('password-expiry.password_column_name')} = Hash::make($data['password']);
```

### How to reproduce the bug

The password is saved in clear, without hashing.

### Package Version

2

### PHP Version

8.2

### Laravel Version

10

**Comment by eighty9nine** [comment]
You have to cast your password as 'hashed'.

```php

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

```

**Comment by masetto** [comment]
ops, sorry!
